# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FitRound <- function(x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0) {
    .Call(`_TimePointsPenalized_FitRound`, x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0)
}

