# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgn <- function(val) {
    .Call(`_TimePointsPenalized_sgn`, val)
}

glmnetSimple <- function(X, Y, lam1) {
    .Call(`_TimePointsPenalized_glmnetSimple`, X, Y, lam1)
}

GetHessian <- function(x, beta, p, y, lam2, w, b, a) {
    invisible(.Call(`_TimePointsPenalized_GetHessian`, x, beta, p, y, lam2, w, b, a))
}

CalculateDeltaIntercept <- function(y, p, w) {
    .Call(`_TimePointsPenalized_CalculateDeltaIntercept`, y, p, w)
}

GroupRound <- function(x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0, M, LLmin) {
    .Call(`_TimePointsPenalized_GroupRound`, x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0, M, LLmin)
}

SingleGeneRound <- function(x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0, M, LLmin) {
    .Call(`_TimePointsPenalized_SingleGeneRound`, x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0, M, LLmin)
}

FitRound <- function(x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0) {
    .Call(`_TimePointsPenalized_FitRound`, x0, y, tV, lam1, lam2, beta, Intercept, w, IndFor0, IndTFor0)
}

